// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingList.Data;

#nullable disable

namespace ShoppingList.Migrations
{
    [DbContext(typeof(MyListDBContext))]
    [Migration("20250515235245_ShoppingItemDetailRelation")]
    partial class ShoppingItemDetailRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingList.Modals.MyShopingList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ItemPrise")
                        .HasColumnType("float");

                    b.Property<double>("ItemQuantity")
                        .HasColumnType("float");

                    b.Property<string>("ListOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("shopingItemDetailsId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("shopingItemDetailsId");

                    b.ToTable("MyShopingLists");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ItemName = "Apples",
                            ItemPrise = 3.9900000000000002,
                            ItemQuantity = 2.5,
                            ListOwner = "Alice"
                        },
                        new
                        {
                            ID = 2,
                            ItemName = "Bread",
                            ItemPrise = 2.4900000000000002,
                            ItemQuantity = 1.0,
                            ListOwner = "Bob"
                        },
                        new
                        {
                            ID = 3,
                            ItemName = "Milk",
                            ItemPrise = 4.25,
                            ItemQuantity = 1.5,
                            ListOwner = "Charlie"
                        },
                        new
                        {
                            ID = 4,
                            ItemName = "Eggs",
                            ItemPrise = 5.9900000000000002,
                            ItemQuantity = 12.0,
                            ListOwner = "Alice"
                        },
                        new
                        {
                            ID = 5,
                            ItemName = "Chicken",
                            ItemQuantity = 1.2,
                            ListOwner = "Bob"
                        });
                });

            modelBuilder.Entity("ShoppingList.Modals.ShoppingItemDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ItemExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShopingListId")
                        .HasColumnType("int");

                    b.Property<double?>("itemMRP")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ShoppingItemDetail");
                });

            modelBuilder.Entity("ShoppingList.Modals.MyShopingList", b =>
                {
                    b.HasOne("ShoppingList.Modals.ShoppingItemDetail", "shopingItemDetails")
                        .WithMany()
                        .HasForeignKey("shopingItemDetailsId");

                    b.Navigation("shopingItemDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
